_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: es
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -59
    expanded: true
    enabled: true
  'menu_link_content:1521f222-4bb2-42f9-b498-cc62f9adb5db_view__comment__page_published':
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 0
    expanded: false
    enabled: false
  entity__commerce_product_attribute__collection:
    menu_name: admin
    parent: commerce.admin_commerce
    weight: 5
    expanded: false
    enabled: true
