entity_type:
  block_content:
    enable: false
  comment:
    enable: false
  commerce_order:
    enable: false
  commerce_product:
    enable: true
  commerce_store:
    enable: false
  field_collection_item:
    enable: false
  mailchimp_campaign:
    enable: false
  node:
    enable: true
  profile:
    enable: false
  shortcut:
    enable: false
  taxonomy_term:
    enable: false
  user:
    enable: false
  menu_link_content:
    enable: false
purge:
  method: time
  read_only: true
  time:
    number: 2
    unit: day
  limit:
    max: null
language:
  user: false
_core:
  default_config_hash: cZCVW5kXkEF8TvwL2yhA0w1uRMuY8F4wgc2s5FENsLY
langcode: es
