general:
  enabled: true
  only_unread: true
  cron_time: '01:00:00'
  log_report: false
  hide_message: false
  mark_read: false
mail:
  from: ''
  subject: 'Aviso de suscripción a nuestros cursos (Kreativdrupal.com)'
  body:
    value: 'Avisos para el usuario: [user:display-name]'
    format: plain_text
  footer:
    value: "Recibes este correo electrónico porque te suscribiste a este informe de avisos en el portal [site:name]. Para configurar la frecuencia con la que recibirás estos informes de avisos: accede a la plataforma [site:login-url] con tus credenciales, pulsas en el enlace 'EDITAR', y en el apartado 'LOGS REPORT FREQUENCY' selecciona la opción que prefieras. Si no deseas recibir más avisos a través del correo electrónico, selecciona la opción: 'Ninguno'.\r\n\r\n"
    format: plain_text
_core:
  default_config_hash: TkyAXpvMb7hm2-d87Wrbqafeiat6ds8Afl2b8XbkTB8
langcode: es
