api_key: aa2e3006be2eb5505c1e84dcca8c01bd-us20
cron: true
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
langcode: es
enable_connected: true
connected_id: d5a5236c4d71e79
connected_paths: 'https://dzahara.kreativdrupal.com/es/confirmar-suscripcion-boletines-0'
